WebAdmin/Controllers/AdminLoginLogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Common;
using Common.AspNetCore.Extensions;
using Common.Config;
using IBLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Models;
using WebAdmin.Models;

namespace WebAdmin.Controllers
{
    public class AdminLoginLogController : BaseController
    {
        private IAdminLoginLogService _adminLoginLogService;

        public AdminLoginLogController(IAdminLoginLogService adminLoginLogService, IAdminOperateLogService operateLogService, IAdminBugService adminBugService, IAdminMenuService adminMenuService, IOptionsSnapshot<SiteConfig> options, IOptionsSnapshot<GatherConfig> gatherOptions) : base(operateLogService, adminBugService, adminMenuService, options, gatherOptions)
        {
            _adminLoginLogService = adminLoginLogService;
        }

        // GET: AdminLoginLog
        public async Task<IActionResult> Index(BaseRequest request)
        {
            try
            {
                ViewBag.PageIndex = request.PageIndex;
                IEnumerable<AdminLoginLog> adminLoginLogList = await _adminLoginLogService.GetAdminLoginLogForAdminListAsync(request);
                await CreateLeftMenuAsync();

                return View(adminLoginLogList as PagedList<AdminLoginLog>);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "登录日志列表错误" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, "登录功能异常" + ex.Message);                
            }
        }

        public async Task<ActionResult> LoginLogToXls(BaseRequest request)
        {
            try
            {
                ViewBag.page = request.PageIndex;//第几页
                ViewBag.Index = (request.PageIndex - 1) * request.PageSize + 1;//第几条
                ViewBag.toIndex = request.PageIndex * request.PageSize;//到多少条
                IEnumerable<AdminLoginLog> adminLoginLogList = _adminLoginLogService.GetAdminLoginLogForAdminList(request);

                var filename = $"登录日志" + DateTime.Now.ToString("yyyyMMdd") + ".xls";
                System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = filename,
                    Inline = false  // false = prompt the user for downloading;  true = browser to try to show the file inline
                };
                Response.Headers.Add("Content-Disposition", cd.ToString());
                Response.ContentType = "application/vnd.ms-excel";

                return View(adminLoginLogList as PagedList<AdminLoginLog>);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "导出登录日志错误" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, "登录功能异常" + ex.Message);
            }
        }


        #region 删除操作
        //// GET: Article/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    try
        //    {
        //        _adminLoginLogService.DelBy(f => f.Id == id);
        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.ErrMsg = ex.Message;
        //        OperateLog.OperateInfo = "删除登录日志错误:" + ex.Message;
        //        OperateLog.IfSuccess = false;
        //        OperateLog.Description = JsonUtil.StringFilter(ex.StackTrace.ToString());
        //        OperateLog.OperateDate = DateTime.Now;
        //        OperateLogService.Add(OperateLog);
        //        return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //    }
        //}

        ////批量删除
        //[HttpPost]
        //public ActionResult Delete(List<int> ids)
        //{
        //    try
        //    {
        //        if (ids != null)
        //        {
        //            _adminLoginLogService.DelBy(f => ids.Contains(f.Id));
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.ErrMsg = ex.Message;
        //        OperateLog.OperateInfo = "批量删除登录日志错误:" + ex.Message;
        //        OperateLog.IfSuccess = false;
        //        OperateLog.Description = JsonUtil.StringFilter(ex.StackTrace.ToString());
        //        OperateLog.OperateDate = DateTime.Now;
        //        OperateLogService.Add(OperateLog);
        //        return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //    }
        //} 
        #endregion
    }
}

WebAdmin/ViewComponents/PaginationViewComponent.cs
/** 
* PaginationViewComponent.cs
*
* 功 能： 分页控件（定义分页参数）
* 类 名： PaginationViewComponent
*
* Ver    变更日期             负责人  变更内容
* ───────────────────────────────────
* V0.01  2018/5/28 10:24:34   李庸    初版
*
*┌──────────────────────────────────┐
*│　此技术信息为本公司机密信息，未经本公司书面同意禁止向第三方披露．　│
*│　版权所有：成都中科创动科技有限公司　　　　　　　　　　　　　　│
*└──────────────────────────────────┘
*/

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RepositoryPattern;

namespace WebAdmin.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        protected readonly IHostingEnvironment Env;
        protected readonly CdyhcdDBContext BusinessDbContext;
        protected readonly ILogger Logger;

        public PaginationViewComponent(IHostingEnvironment env, CdyhcdDBContext context, ILoggerFactory loggerFactory)
        {
            Env = env;
            BusinessDbContext = context;
            Logger = loggerFactory.CreateLogger<PaginationViewComponent>();
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebAdmin/Views/AdminLoginLog/Index.cshtml
@using Models

@model PagedList<AdminLoginLog>

@{
    ViewBag.Title = "登录日志";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" href="@Url.Action("LoginLogToXls", new { PageIndex=ViewBag.PageIndex })"><i class="icon-white"></i> 导出当前页登录日志</a>
            @*<a class="btn blue thickbox" title='添加分类' href="@Url.Action("Create")?TB_iframe=true&height=500&width=450"><i class="icon-plus icon-white"></i> 新增</a>*@
        </div>
    </div>


    @using (Html.BeginForm("Delete", "AdminLoginLog", FormMethod.Post, new { id = "mainForm" }))
    {
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    @*<th style="width: 8px;">
                            <input type="checkbox" id="checkall" class="group-checkable" />
                        </th>*@
                    <th>
                        用户登录名
                    </th>
                    <th>
                        IP地址
                    </th>
                    <th>
                        城市
                    </th>
                    <th>
                        是否成功
                    </th>
                    <th>
                        时间
                    </th>
                    @*<th style="text-align:center">
                            操作
                        </th>*@
                </tr>
            </thead>
            <tbody>
                @{ if (Model != null)
                    {
                        foreach (var m in Model)
                        {
                            <tr>
                                @*<td>
                                        <input type="checkbox" class="checkboxes" name='ids' value='@m.Id' />
                                    </td>*@
                                <td>
                                    @m.UserName
                                </td>
                                <td>
                                    @m.UserIp
                                </td>
                                <td>
                                    @m.City
                                </td>
                                @if (m.IsSuccess == 0)
                                {
                                    <td>是</td>
                                }
                                else
                                {
                                    <td>否</td>
                                }
                                <td>
                                    @m.LoginTime
                                </td>
                                @*<td style="text-align:center">
                                        <a class="btn mini purple" id="delSingle" title='删除此操作日志' href="javascript:if(confirm('确实要删除该内容吗?'))location='@Url.Action("Delete", new { id = m.Id })'">
                                            <i class="icon-edit"></i>
                                            删除
                                        </a>
                                        <input type="hidden" value="@m.Id" name="id" id="id" />
                                    </td>*@
                            </tr>
                        }
                    }
                    else
                    {

                    }
                }
            </tbody>
        </table>
    }
    <div class="dataTables_paginate paging_bootstrap pagination">
        @await Component.InvokeAsync("Pagination")
    </div>
</div>

WebAdmin/Views/AdminLoginLog/LoginLogToXls.cshtml
@using Models

@model PagedList<AdminLoginLog>
@{
    Layout = null;
    string pageTitle = string.Empty;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @{
        pageTitle = "第" + ViewBag.page + "页,第" + ViewBag.Index + "条到" + ViewBag.toIndex + "条" + "登录日志";
    }
    <title>@pageTitle</title>
</head>
<body>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th colspan="6" style="font-size:18px; text-align: center; ">@pageTitle</th>
                </tr>
                <tr>
                    <th rowspan="2" style="text-align: center">
                        序号
                    </th>
                    <th rowspan="2" style="text-align: center">
                        用户登录名
                    </th>
                    <th rowspan="2" style="text-align: center">
                        IP地址
                    </th>
                    <th rowspan="2" style="text-align: center">
                        城市
                    </th>
                    <th rowspan="2" style="text-align: center">
                        操作是否成功
                    </th>
                    <th rowspan="2" style="text-align: center">
                        时间
                    </th>
                </tr>
                <tr></tr>
            </thead>
            <tbody>
                @{
                    int serialNumber = 1;
                }
                @foreach (var m in Model)
                {
                    <tr>
                        <td rowspan="1">
                            @serialNumber
                        </td>
                        <td rowspan="1">
                            @m.UserName
                        </td>
                        <td rowspan="1">
                            @m.UserIp
                        </td>
                        <td rowspan="1">
                            @m.City
                        </td>
                        @{
                            if (m.IsSuccess != null && m.IsSuccess == 1)
                            {
                                <td rowspan="1"> 成功</td>
                            }
                            else
                            {
                                <td rowspan="1"> 失败</td>
                            }
                        }
                        <td rowspan="1">
                            @{ if (m.LoginTime == null)
                                {
                                    <span>--</span>
                                }
                                else
                                {
                                    @m.LoginTime.Value.ToString("yyyy-MM-dd HH:mm:ss")
                                }
                            }
                        </td>
                    </tr>
                    serialNumber++;
                }
            </tbody>
        </table>
    </div>
</body>
</html>