WebAdmin/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Common;
using Common.AspNetCore.Extensions;
using Common.Config;
using IBLL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Models;
using WebAdmin.Models;

namespace WebAdmin.Controllers
{
    public class RoleController : BaseController
    {
        private IAdminRoleService _adminRoleService;
        private IAdminUserService _adminUserService;
        private IAdminRoleAdminMenuButtonService _adminRoleAdminMenuButtonService;

        public RoleController(IAdminRoleService adminRoleService, IAdminUserService adminUserService, IAdminRoleAdminMenuButtonService adminRoleAdminMenuButtonService, IAdminOperateLogService operateLogService, IAdminBugService adminBugService, IAdminMenuService adminMenuService, IOptionsSnapshot<SiteConfig> options, IOptionsSnapshot<GatherConfig> gatherOptions, ILogger<RoleController> logger) : base(operateLogService, adminBugService, adminMenuService, options, gatherOptions)
        {
            _adminRoleService = adminRoleService;
            _adminUserService = adminUserService;
            _adminRoleAdminMenuButtonService = adminRoleAdminMenuButtonService;
            _logger = logger;
        }

        // GET: Role
        public async Task<IActionResult> Index(RoleRequest request)
        {
            try
            {
                if (request == null)
                {
                    ViewBag.ErrMsg = "请传递正确参数!";
                    OperateLog.OperateInfo = "角色查看页面异常";
                    OperateLog.IsSuccess = 0;
                    OperateLog.Description = "未传递角色信息";
                    await MyOperateLogService.AddAsync(OperateLog);
                    return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
                }
                IEnumerable<AdminRoleView> roleList = await _adminRoleService.GetAdminRoleListAsync(request);
                await CreateLeftMenuAsync();

                return View(roleList as PagedList<AdminRoleView>);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色查看页面异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        // GET: Role/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                var model = new AdminRole();
                return View("Edit", model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色编辑页面异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        // POST: Role/Create
        [HttpPost]
        public async Task<IActionResult> Create(AdminRole adminRole)
        {
            try
            {
                var model = new AdminRole();
                await TryUpdateModelAsync(model);

                await _adminRoleService.AddAsync(model);

                return PackagingAjaxMsg(AjaxStatus.IsSuccess, "添加成功！");
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色编辑保存异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        // GET: Role/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            try
            {
                if (id == null || id.Value <= 0)
                {
                    ViewBag.ErrMsg = "请传递正确参数!";
                    OperateLog.OperateInfo = "角色编辑页面异常";
                    OperateLog.IsSuccess = 0;
                    OperateLog.Description = "未传递角色ID";
                    ModelState.AddModelError(string.Empty, "请传递正确参数!");
                    await MyOperateLogService.AddAsync(OperateLog);
                    return View();
                }

                AdminRole model = await _adminRoleService.GetModelAsync(id.Value);

                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色编辑页面异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                ModelState.AddModelError(string.Empty, "内部错误，请联系管理员!");
                return View();
            }
        }

        // POST: Role/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(AdminRole adminRole)
        {
            try
            {
                if (adminRole == null || adminRole.Id <= 0)
                {
                    ViewBag.ErrMsg = "请传递正确参数!";
                    OperateLog.OperateInfo = "角色编辑保存异常";
                    OperateLog.IsSuccess = 0;
                    OperateLog.Description = "未传递角色ID";
                    ModelState.AddModelError(string.Empty, "请传递正确参数!");
                    await MyOperateLogService.AddAsync(OperateLog);
                    return View();
                }

                var model = await _adminRoleService.GetModelByAsync(f => f.Id == adminRole.Id);
                await TryUpdateModelAsync<AdminRole>(model);

                _adminRoleService.Modify(model);

                return PackagingAjaxMsg(AjaxStatus.IsSuccess, "修改成功!");
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色编辑保存异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                ModelState.AddModelError(string.Empty, "内部错误，请联系管理员!");
                return View();
            }
        }

        // GET: Role/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                if (id == null || id.Value <= 0)
                {
                    ViewBag.ErrMsg = "请传递正确参数!";
                    OperateLog.OperateInfo = "角色删除功能异常";
                    OperateLog.IsSuccess = 0;
                    OperateLog.Description = "未传递角色ID";
                    await MyOperateLogService.AddAsync(OperateLog);
                    return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
                }
                _adminRoleService.DelIncludeRelatedDataAsync(id.Value);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;

                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "角色删除功能异常" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        //批量删除
        [HttpPost]
        public async Task<IActionResult> Delete(List<int> ids)
        {
            try
            {

WebAdmin/ViewComponents/PaginationViewComponent.cs
/** 
* PaginationViewComponent.cs
*
* 功 能： 分页控件（定义分页参数）
* 类 名： PaginationViewComponent
*
* Ver    变更日期             负责人  变更内容
* ───────────────────────────────────
* V0.01  2018/5/28 10:24:34   李庸    初版
*
*┌──────────────────────────────────┐
*│　此技术信息为本公司机密信息，未经本公司书面同意禁止向第三方披露．　│
*│　版权所有：成都中科创动科技有限公司　　　　　　　　　　　　　　│
*└──────────────────────────────────┘
*/

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RepositoryPattern;

namespace WebAdmin.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        protected readonly IHostingEnvironment Env;
        protected readonly CdyhcdDBContext BusinessDbContext;
        protected readonly ILogger Logger;

        public PaginationViewComponent(IHostingEnvironment env, CdyhcdDBContext context, ILoggerFactory loggerFactory)
        {
            Env = env;
            BusinessDbContext = context;
            Logger = loggerFactory.CreateLogger<PaginationViewComponent>();
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebAdmin/Views/Role/Edit.cshtml
@model Models.AdminRole

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@section PageSpecificStyleSheetIncludes{
}

@section PageSpecificJavascriptIncludes{
}
@section MainContent{
    <div class="tabbable tabbable-custom">
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="portlet-body form-horizontal form-bordered form-row-stripped">
                    <div class="row-fluid">
                        <div class="control-group">
                            <label class="control-label"><span class="required">*</span>角色名称：</label>
                            <div class="controls">
                                @Html.TextBoxFor(m => m.RoleName, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.RoleName)</span>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">角色介绍：</label>
                            <div class="controls">
                                @Html.TextAreaFor(m => m.Description, new { @class = "m-wrap large" })
                                <span class="help-inline">@Html.ValidationMessageFor(m => m.Description)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebAdmin/Views/Role/EditRoleMenu.cshtml
@using Common

@model RoleMenuViewModel

@{
    ViewBag.Title = "EditRoleMenu";
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@section PageSpecificStyleSheetIncludes{
    <link href="~/lib/jquery-easyui-1.5/themes/bootstrap/easyui.css" rel="stylesheet" />
}
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript" src="~/lib/jquery-easyui-1.5/plugins/jquery.tree.js"></script>
    <script type="text/javascript" src="~/lib/jquery-easyui-1.5/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="~/lib/jquery-easyui-1.5/locale/easyui-lang-zh_CN.js"></script>
    <script type="text/javascript">

        $(function() {            
            menuTreeBind(0, @ViewBag.RoleId);
            $(".MenuTree .validatebox-readonly").removeAttr("readonly");
        });

        //绑定文章类别(类别号)
        function menuTreeBind(menuId, roleId) {
            $('#MenuTree')
                .tree({
                    url: "/Menu/GetAdminUserMenuTreeJson?menuId=" + menuId + "&roleId=" + roleId,
                    onlyLeafCheck: true,
                    checkbox: true,
                    disabled: false,
                    readonly: false,
                    loadFilter: function(data) {
                        return data;
                    },
                    onCheck: function(node, checked) {
                        //返回已勾选集合
                        var nodes = $("#MenuTree").tree('getChecked');
                        var checkeds = "";
                        $.each(nodes,
                            function(index, e) {
                                checkeds += e.id + ",";
                                //把父节点加入
                                var parentNode = $("#MenuTree").tree('getParent', e.target);
                                var checkedLIst = checkeds.split(',');
                                var haveParent = false;
                                for (var i = 0; i < checkedLIst.length; i++) {
                                    if (checkedLIst[i] === parentNode.id) { //如果数组中某个元素和你想要测试的元素对象element相等，则证明数组中包含这个元素，返回true
                                        haveParent = true;
                                        return;
                                    }
                                }
                                if (!haveParent) {
                                    checkeds += parentNode.id + ",";
                                }
                            });
                        if (checkeds.substring(checkeds.length - 1, checkeds.length) === ",") {
                            checkeds = checkeds.substring(0, checkeds.length - 1);
                        }
                        $('#CheckedMenuIds').val(checkeds);
                    }
                });
        }
    </script>
}
@section MainContent{
    <span id="MenuTree" name="MenuTree" class="easyui-tree" style="width: 220px;">
    </span>
    @Html.HiddenFor(m=>m.RoleId)
    @Html.HiddenFor(m=>m.CheckedMenuIds)
}

WebAdmin/Views/Role/Index.cshtml
@using Models

@model PagedList<AdminRoleView>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section PageSpecificStyleSheetIncludes{

}
@section PageSpecificJavascriptIncludes{
}
<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>
            <a class="btn blue thickbox" title='添加新角色' href="@Url.Action("Create")?TB_iframe=true&height=300&width=350"><i class="icon-plus icon-white"></i> 新增</a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, FormMethod.Get, new { id = "search" }))
        {
            <div class="dataTables_filter">
                <label>
                    <button type="submit" class="btn">搜索 <i class="icon-search"></i></button>
                </label>
                <label>
                    <span>角色名称：</span>
                    @Html.TextBox("RoleName", "", new { @class = "m-wrap small" })
                </label>
            </div>
        }
    </div>
</div>

@using (Html.BeginForm("Delete", "Role", FormMethod.Post, new { id = "mainForm" }))
{
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th style="width: 8px;">
                    <input type="checkbox" id="checkall" class="group-checkable" />
                </th>
                <th>
                    角色名称
                </th>
                <th>
                    角色描述
                </th>
                <th>
                    添加时间
                </th>
                <th>
                    修改时间
                </th>
                <th style="text-align:center">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="checkboxes" name='ids' value='@m.Id' />
                    </td>
                    <td>
                        @m.RoleName
                    </td>
                    <td>
                        @m.Description
                    </td>
                    <td>
                        @m.AddTime
                    </td>
                    <td>
                        @m.EditTime
                    </td>
                    <td style="text-align: center">
                        <a class="btn mini purple thickbox" title='编辑此角色' href="@Url.Action("Edit", new {id = m.Id})?TB_iframe=true&height=300&width=350">
                            <i class="icon-edit"></i>
                            编辑
                        </a>
                        <a class="btn mini purple" id="delSingle" title='删除此角色' href="javascript:if(confirm('确实要删除该角色吗?'))location='@Url.Action("Delete", new {id = m.Id})'">
                            <i class="icon-edit"></i>
                            删除
                        </a>
                        <a class="btn mini purple thickbox" title='查看角色成员' href="@Url.Action("RoleUserIndex", new {RoleId = m.Id, PageSize=10})?TB_iframe=true&height=700&width=850">
                            <i class="icon-edit"></i>
                            查看角色成员
                        </a>
                        <a class="btn mini purple thickbox" title='编辑角色菜单' href="@Url.Action("EditRoleMenu", new {id = m.Id})?TB_iframe=true&height=700&width=250">
                            <i class="icon-edit"></i>
                            编辑角色菜单
                        </a>
                        <input type="hidden" value="@m.Id" name="Id" id="Id" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @await Component.InvokeAsync("Pagination")
</div>

WebAdmin/Views/Role/RoleUserIndex.cshtml
@using Models

@model PagedList<Models.AdminUserView>

@{
    Layout = "~/Views/Shared/_Layout.List.cshtml";
}
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>
                序号
            </th>
            <th>
                登录名
            </th>
            <th>
                姓名
            </th>
            <th>
                启用
            </th>
            <th>
                改密
            </th>
            <th>
                添加时间
            </th>
        </tr>
    </thead>
    <tbody>
        @{
            int eax = 1;
            int modelNo = 0;
        }
        @foreach (var m in Model)
        {
            modelNo = Model.CurrentPageIndex - 1 + eax;
            <tr>
                <td>
                    @modelNo
                </td>
                <td>
                    @m.UserName
                </td>
                <td>
                    @m.Name
                </td>
                <td>
                    @(m.IsAble == null ? Html.CheckBox("IsAble", false, new { disabled = true }) : Html.CheckBox("IsAble", true, new { disabled = true }))

                </td>
                <td>
                    @(m.IsChangePwd == null ? Html.CheckBox("IfChangePwd", false, new { disabled = true }) : Html.CheckBox("IfChangePwd", true, new { disabled = true }))

                </td>
                <td>
                    @m.AddTime
                </td>
            </tr>
            eax++;
        }
    </tbody>
</table>

<div class="dataTables_paginate paging_bootstrap pagination">
    @await Component.InvokeAsync("Pagination")
</div>