WebAdmin/Controllers/AdminOperateLogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Common;
using Common.AspNetCore.Extensions;
using Common.Config;
using IBLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Models;
using WebAdmin.Models;

namespace WebAdmin.Controllers
{
    public class AdminOperateLogController : BaseController
    {
        public AdminOperateLogController(IAdminOperateLogService operateLogService, IAdminBugService adminBugService, IAdminMenuService adminMenuService, IOptionsSnapshot<SiteConfig> options, IOptionsSnapshot<GatherConfig> gatherOptions) : base(operateLogService, adminBugService, adminMenuService, options, gatherOptions)
        {
        }

        //GET: AdminOperateLog
        public async Task<IActionResult> Index(BaseRequest request)
        {
            try
            {
                ViewBag.PageIndex = request.PageIndex;
                IEnumerable<AdminOperateLog> adminOperateLogList = await MyOperateLogService.GetOperateLogForAdminListAsync(request);
                await CreateLeftMenuAsync();

                return View(adminOperateLogList as PagedList<AdminOperateLog>);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "操作日志列表错误" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
               await MyAdminBugService.AddAsync(Bug);
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        /// <summary>
        /// 导出操作日志到Excel
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        public async Task<IActionResult> OperateLogToXls(BaseRequest request)
        {
            try
            {
                ViewBag.page = request.PageIndex;//第几页
                ViewBag.Index = (request.PageIndex - 1) * request.PageSize + 1;//第几条
                ViewBag.toIndex = request.PageIndex * request.PageSize;//到多少条
                IEnumerable<AdminOperateLog> adminOperateLogList = await MyOperateLogService.GetOperateLogForAdminListAsync(request);

                var filename = $"操作日志" + DateTime.Now.ToString("yyyyMMdd") + ".xls";
                System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = filename,
                    Inline = false  // false = prompt the user for downloading;  true = browser to try to show the file inline
                };
                Response.Headers.Add("Content-Disposition", cd.ToString());
                Response.ContentType = "application/vnd.ms-excel;utf-8";

                return View(adminOperateLogList as PagedList<AdminOperateLog>);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "导出操作日志错误" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);
            }
        }

        /// <summary>
        /// 查看操作日志详情
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> ViewDescription(int? id)
        {
            try
            {
                AdminOperateLog AdminOperateLogModel = await MyOperateLogService.GetModelByAsync(a => a.Id == id);

                return View(AdminOperateLogModel);
            }
            catch (Exception ex)
            {
                ViewBag.ErrMsg = ex.Message;
                Bug = new AdminBug
                {
                    UserIp = HttpContext.GetUserIp(),
                    IsShow = 1,
                    IsSolve = 0,
                    BugInfo = "查看详细列表信息错误" + ex.Message,
                    BugMessage = JsonUtil.StringFilter(ex.StackTrace.ToString()),
                    UserName = User != null && User.Identity != null ? User.Identity.Name : "",
                    AddTime = DateTime.Now,
                    EditTime = DateTime.Now
                };
                return PackagingAjaxMsg(AjaxStatus.Err, Bug.BugInfo);                
            }
        }

        #region 删除操作

        //// GET: Article/Delete/5
        //public async Task<IActionResult> Delete(int id)
        //{
        //    try
        //    {
        //        MyOperateLogService.DelBy(f => f.Id == id);
        //        return RedirectToAction("Index");
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.ErrMsg = ex.Message;
        //        OperateLog.OperateInfo = "删除操作日志错误:" + ex.Message;
        //        OperateLog.IfSuccess = false;
        //        OperateLog.Description = JsonUtil.StringFilter(ex.StackTrace.ToString());
        //        OperateLog.OperateDate = DateTime.Now;
        //        OperateLogService.Add(OperateLog);
        //        return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //    }
        //}

        ////批量删除
        //[HttpPost]
        //public async Task<IActionResult> Delete(List<int> ids)
        //{
        //    try
        //    {
        //        if (ids != null)
        //        {
        //            MyOperateLogService.DelBy(f => ids.Contains(f.Id));
        //            return RedirectToAction("Index");
        //        }
        //        else
        //        {
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        ViewBag.ErrMsg = ex.Message;
        //        OperateLog.OperateInfo = "批量删除操作日志错误:" + ex.Message;
        //        OperateLog.IfSuccess = false;
        //        OperateLog.Description = JsonUtil.StringFilter(ex.StackTrace.ToString());
        //        OperateLog.OperateDate = DateTime.Now;
        //        OperateLogService.Add(OperateLog);
        //        return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //    }
        //} 
        #endregion
    }
}

WebAdmin/ViewComponents/PaginationViewComponent.cs
/** 
* PaginationViewComponent.cs
*
* 功 能： 分页控件（定义分页参数）
* 类 名： PaginationViewComponent
*
* Ver    变更日期             负责人  变更内容
* ───────────────────────────────────
* V0.01  2018/5/28 10:24:34   李庸    初版
*
*┌──────────────────────────────────┐
*│　此技术信息为本公司机密信息，未经本公司书面同意禁止向第三方披露．　│
*│　版权所有：成都中科创动科技有限公司　　　　　　　　　　　　　　│
*└──────────────────────────────────┘
*/

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RepositoryPattern;

namespace WebAdmin.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        protected readonly IHostingEnvironment Env;
        protected readonly CdyhcdDBContext BusinessDbContext;
        protected readonly ILogger Logger;

        public PaginationViewComponent(IHostingEnvironment env, CdyhcdDBContext context, ILoggerFactory loggerFactory)
        {
            Env = env;
            BusinessDbContext = context;
            Logger = loggerFactory.CreateLogger<PaginationViewComponent>();
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

WebAdmin/Views/AdminOperateLog/Index.cshtml
@using Models

@model PagedList<AdminOperateLog>

@{
    ViewBag.Title = "操作日志";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" href="@Url.Action("OperateLogToXls", new { PageIndex=ViewBag.PageIndex })"><i class="icon-white"></i> 导出当前页操作日志</a>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "AdminOperateLog", FormMethod.Post, new { id = "mainForm" }))
    {
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    @*<th style="width: 8px;">
                            <input type="checkbox" id="checkall" class="group-checkable" />
                        </th>*@
                    <th>
                        用户登录名
                    </th>
                    <th>
                        IP地址
                    </th>
                    <th>
                        操作信息
                    </th>
                    <th>
                        错误描述
                    </th>
                    <th>
                        操作是否成功
                    </th>
                    <th>
                        时间
                    </th>
                    @*<th style="text-align:center">
                            操作
                        </th>*@
                </tr>
            </thead>
            <tbody>
                @{ if (Model != null)
                    {
                        foreach (var m in Model)
                        {
                            <tr>
                                @*<td>
                                        <input type="checkbox" class="checkboxes" name='ids' value='@m.Id' />
                                    </td>*@
                                <td>
                                    @m.UserName
                                </td>
                                <td>
                                    @m.UserIp
                                </td>
                                <td>
                                    @{if (m.OperateInfo != null && m.OperateInfo.Length > 20)
                                        {
                                            @m.OperateInfo.Substring(0, 19)
                                        }
                                        else
                                        {
                                            @m.OperateInfo
                                        }
                                    }
                                </td>
                                <td>
                                    <a class="btn mini purple thickbox" title='查看详细描述' href="@Url.Action("ViewDescription", new { id = m.Id })?TB_iframe=true&height=500&width=600">
                                        <i class="icon-edit"></i>
                                        查看详细描述
                                    </a>
                                </td>
                                @{ if (m.IsSuccess != null && m.IsSuccess == 1)
                                    {
                                        <td>是</td>
                                    }
                                    else
                                    {
                                        <td>否</td>
                                    }
                                }
                                <td>
                                    @{ if (m.OperateTime == null)
                                        {
                                            <span>--</span>
                                        }
                                        else
                                        {
                                            @m.OperateTime.Value.ToString("yyyy-MM-dd HH:mm:ss")
                                        }
                                    }
                                </td>
                                @*<td style="text-align:center">
                                        <a class="btn mini purple" id="delSingle" title='删除此操作日志' href="javascript:if(confirm('确实要删除该内容吗?'))location='@Url.Action("Delete", new { id = m.Id })'">
                                            <i class="icon-edit"></i>
                                            删除
                                        </a>
                                        <input type="hidden" value="@m.Id" name="id" id="id" />
                                    </td>*@
                            </tr>
                        }
                    }
                    else
                    {

                    }
                }
            </tbody>
        </table>
    }
    <div class="dataTables_paginate paging_bootstrap pagination">
        @await Component.InvokeAsync("Pagination")
    </div>
</div>

WebAdmin/Views/AdminOperateLog/OperateLogToXls.cshtml
@using Models

@model PagedList<AdminOperateLog>
@{
    Layout = null;
    string pageTitle = string.Empty;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @{
        pageTitle = "第" + ViewBag.page + "页,第" + ViewBag.Index + "条到" + ViewBag.toIndex + "条" + "操作日志";
    }
    <title>@pageTitle</title>
</head>
<body>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <th colspan="6" style="font-size:18px; text-align: center; ">@pageTitle</th>
                </tr>
                <tr>
                    <th rowspan="2" style="text-align: center">
                        序号
                    </th>
                    <th rowspan="2" style="text-align: center">
                        用户登录名
                    </th>
                    <th rowspan="2" style="text-align: center">
                        IP地址
                    </th>
                    <th rowspan="2" style="text-align: center">
                        操作信息
                    </th>
                    <th rowspan="2" style="text-align: center">
                        具体描述
                    </th>
                    <th rowspan="2" style="text-align: center">
                        操作是否成功
                    </th>
                    <th rowspan="2" style="text-align: center">
                        时间
                    </th>
                </tr>
                <tr></tr>
            </thead>
            <tbody>
                @{
                    int serialNumber = 1;
                }
                @foreach (var m in Model)
                {
                    <tr>
                        <td rowspan="1">
                            @serialNumber
                        </td>
                        <td rowspan="1">
                            @m.UserName
                        </td>
                        <td rowspan="1">
                            @m.UserIp
                        </td>
                        <td rowspan="1">
                            @m.OperateInfo
                        </td>
                        <td rowspan="1">
                            @m.Description
                        </td>
                        @{
                            if (m.IsSuccess != null && m.IsSuccess == 1)
                            {
                                <td rowspan="1"> 成功</td>
                            }
                            else
                            {
                                <td rowspan="1"> 失败</td>
                            }
                        }
                        <td rowspan="1">
                            @{ if (m.OperateTime == null)
                                {
                                    <span>--</span>
                                }
                                else
                                {
                                    @m.OperateTime.Value.ToString("yyyy-MM-dd HH:mm:ss")
                                }
                            }
                        </td>
                    </tr>
                    serialNumber++;
                }
            </tbody>
        </table>
    </div>
</body>
</html>

WebAdmin/Views/AdminOperateLog/ViewDescription.cshtml
@using Common
@model Models.AdminOperateLog
@{
    ViewBag.Title = "ViewDescription";
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}

@section MainContent{
    <div class="tabbable tabbable-custom">
        <div class="tab-content">
            <div class="tab-pane active" id="tab1">
                <div class="portlet-body form-horizontal form-bordered form-row-stripped">
                    <div class="row-fluid">
                        <div class="control-group">
                            <label class="control-label">操作信息：</label>
                            <div class="controls">
                                @Html.TextAreaFor(m => m.OperateInfo, new { @class = "m-wrap large", style = "width:220px;height:120px;" })
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">错误详细描述：</label>
                            <div class="controls">
                                @Html.TextAreaFor(m => m.Description, new { @class = "m-wrap large", style = "width:220px;height:200px;" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}