YhcdWebsite/Controllers/ArticleController.cs
using Common.AspNetCore.Extensions;
using IBLL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using YhcdWebsite.Config;
using YhcdWebsite.Models;

namespace YhcdWebsite.Controllers
{
    public class ArticleController : BaseController
    {
        private readonly IArticleService _articleService;
        
        public ArticleController(IArticleService articleService, IArticleClassService articleClassService, IOptions<SiteConfig> options) : base(articleClassService, options)
        {
            _articleService = articleService;
        }

        // GET: Article
        public async Task<IActionResult> List(int? id, ArticleRequest request)
        {
            try
            {
                if (id == null || id == 0)
                {
                    return new LocalRedirectResult("/errors/400");
                }

                request.ClassId = id.Value;
                ViewBag.KeyWord = request.Title;
                ViewBag.CurrentPageIndex = request.PageIndex <= 1 ? 1 : request.PageIndex;
                ViewBag.TotalPageCount = 1;

                ViewBag.ClassId = request == null ? 0 : request.ClassId;               

                if (request.PageSize <= 0)
                {
                    request.PageSize = SiteConfigSettings.DefaultPageCount;
                }
                IEnumerable<ArticleView> articleList = await _articleService.GetArticleListBySqlAsync(request);
                return View(articleList as PagedList<ArticleView>);
            }
            catch(Exception ex)
            {
                _logger.Error($"于{DateTime.Now}在IP:{HttpContext.GetUserIp()}访问文章列表页报\"{ex.Message}\"，错误详细信息：{ex.StackTrace.ToString()}.");
                return new LocalRedirectResult("/errors/500");
                //return View("Error", new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }            
        }

        // GET: Article/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var article = await _articleService.GetModelAsync(id.Value);
                if (article == null)
                {
                    return NotFound();
                }
                return View(article);
            }
            catch (Exception ex)
            {
                _logger.Error($"于{DateTime.Now}在IP:{HttpContext.GetUserIp()}访问文章详细页报\"{ex.Message}\"，错误详细信息：{ex.StackTrace.ToString()}.");
                return new LocalRedirectResult("/errors/500");
            }
        }
        private bool ArticleExists(int id)
        {
            return _articleService.GetModel(id) == null;
        }
    }
}

YhcdWebsite/ViewComponents/PaginationViewComponent.cs
/** 
* PaginationViewComponent.cs
*
* 功 能： 分页控件（定义分页参数）
* 类 名： PaginationViewComponent
*
* Ver    变更日期             负责人  变更内容
* ───────────────────────────────────
* V0.01  2018/5/28 10:24:34   李庸    初版
*
*┌──────────────────────────────────┐
*│　此技术信息为本公司机密信息，未经本公司书面同意禁止向第三方披露．　│
*│　版权所有：成都中科创动科技有限公司　　　　　　　　　　　　　　│
*└──────────────────────────────────┘
*/

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RepositoryPattern;

namespace YhcdWebsite.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        protected readonly IHostingEnvironment Env;
        protected readonly CdyhcdDBContext BusinessDbContext;
        protected readonly ILogger Logger;

        public PaginationViewComponent(IHostingEnvironment env, CdyhcdDBContext context, ILoggerFactory loggerFactory)
        {
            Env = env;
            BusinessDbContext = context;
            Logger = loggerFactory.CreateLogger<PaginationViewComponent>();
        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

YhcdWebsite/Views/Article/Create.cshtml
@model Models.Article

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitleColor" class="control-label"></label>
                <input asp-for="TitleColor" class="form-control" />
                <span asp-validation-for="TitleColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Introduce" class="control-label"></label>
                <input asp-for="Introduce" class="form-control" />
                <span asp-validation-for="Introduce" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntroduceImg" class="control-label"></label>
                <input asp-for="IntroduceImg" class="form-control" />
                <span asp-validation-for="IntroduceImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LookCount" class="control-label"></label>
                <input asp-for="LookCount" class="form-control" />
                <span asp-validation-for="LookCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddHtmlurl" class="control-label"></label>
                <input asp-for="AddHtmlurl" class="form-control" />
                <span asp-validation-for="AddHtmlurl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sort" class="control-label"></label>
                <input asp-for="Sort" class="form-control" />
                <span asp-validation-for="Sort" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddTime" class="control-label"></label>
                <input asp-for="AddTime" class="form-control" />
                <span asp-validation-for="AddTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EditTime" class="control-label"></label>
                <input asp-for="EditTime" class="form-control" />
                <span asp-validation-for="EditTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

YhcdWebsite/Views/Article/Delete.cshtml
@model Models.Article

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TitleColor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TitleColor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Introduce)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Introduce)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IntroduceImg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IntroduceImg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LookCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LookCount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddHtmlurl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddHtmlurl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsTop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsTop)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsMarquee)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsMarquee)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sort)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sort)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EditTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EditTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDel)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

YhcdWebsite/Views/Article/Details.cshtml
@model Models.Article
<!--content-->
<section class="content">
    <section class="container">
        @Html.Partial("LeftMenuPartial")
        <section class="services-content pull-left">
            <section class="crumb">
                <img src="~/images/icon-home.png" alt="首页" />&nbsp;&nbsp;<a href="/">首页</a> > 行业资讯
            </section>
            <section class="news">
                <section class="news-title">
                    @Html.DisplayFor(model => model.Title)
                </section>
                <section class="news-time">
                    @Model.AddTime.Value.ToString("yyyy-MM-dd")&nbsp;&nbsp;
                    @Html.DisplayFor(model => model.Origin)
                </section>
                <section class="news-content">
                    @Html.Raw(Model.Content)
                </section>
            </section>
        </section>
    </section>
</section>
<!--content-->
@section Scripts {
    <environment include="Development">
        <script src="~/js/Json/LeftNewsMenu.js"></script>
        <script src="~/js/leftNewsMenu.js"></script>
        <script src="~/js/timeStyle.js"></script>
        <script src="~/js/base-loading.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/leftNewsMenu.min.js" asp-append-version="true"></script>
        <script src="~/js/timeStyle.min.js" asp-append-version="true"></script>
        <script src="~/js/base-loading.min.js" asp-append-version="true"></script>
    </environment>
    <script>
        $(document).ready(function () {
            var currentNewsMenu = leftNewsMenu.find(function (obj) {
                return @Model.ClassId === obj.id;
            });
            if (@Model.ClassId && @Model.ClassId > 0 && currentNewsMenu) {
                $(".crumb").append(" > " + currentNewsMenu.menuTitle);
                $("#menu-left a").parent().removeClass("current");
                $("#menu-left a[href$='/Article/List-" +@Model.ClassId+".html']").parent().addClass("current");
                $("#top a[href='/Article/List-2.html'").parent().addClass("current");
            }
        });
    </script>
}

YhcdWebsite/Views/Article/Edit.cshtml
@model Models.Article

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Article</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ClassId" class="control-label"></label>
                <input asp-for="ClassId" class="form-control" />
                <span asp-validation-for="ClassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TitleColor" class="control-label"></label>
                <input asp-for="TitleColor" class="form-control" />
                <span asp-validation-for="TitleColor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Introduce" class="control-label"></label>
                <input asp-for="Introduce" class="form-control" />
                <span asp-validation-for="Introduce" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntroduceImg" class="control-label"></label>
                <input asp-for="IntroduceImg" class="form-control" />
                <span asp-validation-for="IntroduceImg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Origin" class="control-label"></label>
                <input asp-for="Origin" class="form-control" />
                <span asp-validation-for="Origin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LookCount" class="control-label"></label>
                <input asp-for="LookCount" class="form-control" />
                <span asp-validation-for="LookCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddHtmlurl" class="control-label"></label>
                <input asp-for="AddHtmlurl" class="form-control" />
                <span asp-validation-for="AddHtmlurl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsTop" class="control-label"></label>
                <input asp-for="IsTop" class="form-control" />
                <span asp-validation-for="IsTop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsMarquee" class="control-label"></label>
                <input asp-for="IsMarquee" class="form-control" />
                <span asp-validation-for="IsMarquee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sort" class="control-label"></label>
                <input asp-for="Sort" class="form-control" />
                <span asp-validation-for="Sort" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AddTime" class="control-label"></label>
                <input asp-for="AddTime" class="form-control" />
                <span asp-validation-for="AddTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EditTime" class="control-label"></label>
                <input asp-for="EditTime" class="form-control" />
                <span asp-validation-for="EditTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsDel" class="control-label"></label>
                <input asp-for="IsDel" class="form-control" />
                <span asp-validation-for="IsDel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

YhcdWebsite/Views/Article/List.cshtml
@model IEnumerable<Models.ArticleView>
@{ 
    ViewBag.Title = "行业资讯";
}
<!--content-->
<section class="content">
    <section class="container">
        @Html.Partial("LeftMenuPartial")
        <section class="services-content pull-left">
            <section class="crumb">
                <img src="~/images/icon-home.png" alt="首页" />&nbsp;&nbsp;<a href="/">首页</a> > 行业资讯
            </section>
            <section class="content-list">
                @if (Model.Count() <= 0) {
                    <h3 class="text-center">暂无内容</h3>
                }
                @foreach (var item in Model)
                {
                    <ul>
                        <li @*class="calendar"*@>
                            @Html.DisplayFor(modelItem => item.AddTime.Value, "ShortDate")
                        </li>
                        <li class="content-title">
                                <a asp-area="" asp-controller="Article" asp-action="Details" asp-route-id="@item.Id" title="@Html.DisplayFor(modelItem => item.Title)" target="_blank">@Html.DisplayFor(modelItem => item.Title)</a>
                            @*<div class="summary hidden-sm hidden-xs hidden-md" title="@Html.DisplayFor(modelItem => item.Introduce)">
                                @Html.DisplayFor(modelItem => item.Introduce)
                            </div>*@
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                }
            </section>
            <div class="pagination text-center">
                @await Component.InvokeAsync("Pagination")
            </div>
        </section>
    </section>
</section>
<!--content-->
@section Scripts {
<environment include="Development">
    <script src="~/js/Json/LeftNewsMenu.js"></script>
    <script src="~/js/leftNewsMenu.js"></script>
    @*<script src="~/js/timeStyle.js"></script>*@
    <script src="~/js/base-loading.js"></script>   
</environment>
<environment exclude="Development">
    <script src="~/js/leftNewsMenu.min.js" asp-append-version="true"></script>
    <script src="~/js/timeStyle.min.js" asp-append-version="true"></script>
    <script src="~/js/base-loading.min.js" asp-append-version="true"></script>
</environment>
}